export const ADD_LAUNCH_REQUEST = 'ADD_LAUNCH_REQUEST'
export const ADD_LAUNCH_SUCCESS = 'ADD_LAUNCH_SUCCESS'
export const ADD_LAUNCH_FAIL = 'ADD_LAUNCH_FAIL'

export const GET_LAUNCH_REQUEST = 'GET_LAUNCH_REQUEST'
export const GET_LAUNCH_SUCCESS = 'GET_LAUNCH_SUCCESS'
export const GET_LAUNCH_FAIL = 'GET_LAUNCH_FAIL'

export const EDIT_LAUNCH_REQUEST = 'EDIT_LAUNCH_REQUEST'
export const EDIT_LAUNCH_SUCCESS = 'EDIT_LAUNCH_SUCCESS'
export const EDIT_LAUNCH_FAIL = 'EDIT_LAUNCH_FAIL'

export const DELETE_LAUNCH_REQUEST = 'DELETE_LAUNCH_REQUEST'
export const DELETE_LAUNCH_SUCCESS = 'DELETE_LAUNCH_SUCCESS'
export const DELETE_LAUNCH_FAIL = 'DELETE_LAUNCH_FAIL'

export const GET_LAUNCHES_REQUEST = 'GET_LAUNCHES_REQUEST'
export const GET_LAUNCHES_SUCCESS = 'GET_LAUNCHES_SUCCESS'
export const GET_LAUNCHES_FAIL = 'GET_LAUNCHES_FAIL'