export const NEW_UPDATE_REQUEST = 'NEW_UPDATE_REQUEST'
export const NEW_UPDATE_SUCCESS = 'NEW_UPDATE_SUCCESS'
export const NEW_UPDATE_FAIL = 'NEW_UPDATE_FAIL'

export const GET_UPDATES_REQUEST = 'GET_UPDATES_REQUEST'
export const GET_UPDATES_SUCCESS = 'GET_UPDATES_SUCCESS'
export const GET_UPDATES_FAIL = 'GET_UPDATES_FAIL'

export const EDIT_UPDATE_REQUEST = 'EDIT_UPDATE_REQUEST'
export const EDIT_UPDATE_SUCCESS = 'EDIT_UPDATE_SUCCESS'
export const EDIT_UPDATE_FAIL = 'EDIT_UPDATE_FAIL'

export const DELETE_UPDATE_REQUEST = 'DELETE_UPDATE_REQUEST'
export const DELETE_UPDATE_SUCCESS = 'DELETE_UPDATE_SUCCESS'
export const DELETE_UPDATE_FAIL = 'DELETE_UPDATE_FAIL'