export const NEW_VEHICLE_REQUEST = 'NEW_VEHICLE_REQUEST'
export const NEW_VEHICLE_SUCCESS = 'NEW_VEHICLE_SUCCESS'
export const NEW_VEHICLE_FAIL = 'NEW_VEHICLE_FAIL'

export const GET_VEHICLES_REQUEST = 'GET_VEHICLES_REQUEST'
export const GET_VEHICLES_SUCCESS = 'GET_VEHICLES_SUCCESS'
export const GET_VEHICLES_FAIL = 'GET_VEHICLES_FAIL'

export const EDIT_VEHICLE_REQUEST = 'EDIT_VEHICLE_REQUEST'
export const EDIT_VEHICLE_SUCCESS = 'EDIT_VEHICLE_SUCCESS'
export const EDIT_VEHICLE_FAIL = 'EDIT_VEHICLE_FAIL'

export const DELETE_VEHICLE_REQUEST = 'DELETE_VEHICLE_REQUEST'
export const DELETE_VEHICLE_SUCCESS = 'DELETE_VEHICLE_SUCCESS'
export const DELETE_VEHICLE_FAIL = 'DELETE_VEHICLE_FAIL'